blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2018/4/19 15:46
# @File    : urls.py

from django.conf.urls import url
from blog.feeds import AllPostsRssFeed
from . import views

app_name = 'blog'
urlpatterns = [
    # django2.0后使用path，不过用1.0的项目比较多
    # path('post/<int:pk>/', views.detail, name='detail'),
    # as_view将类视图转换为函数
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9])/$', views.TagView.as_view(), name="tag"),
    url(r'^about/$', views.aboutpage, name='about'),
    url(r'collection/$', views.collection, name='collection'),
    # 简单搜索
    # url(r'^search/$', views.search, name="search"),
    # RSS订阅
    url(r'^all/rss/$', AllPostsRssFeed(), name="rss"),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    # haystack全局搜索
    path('search/', include('haystack.urls')),
]

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.


@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

templates/search/search.html
{% extends 'base.html' %}
{% load highlight %}

{% block main %}
    {% if query %}
        {% for result in page.object_list %}
            <article class="post post-{{ result.object.pk }}">
                <header class="entry-header">
                    <h1 class="entry-title">
                        <a href="{{ result.object.get_absolute_url }}">
                            {% highlight result.object.title with query %}
                        </a>
                    </h1>
                    <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' result.object.category.pk %}">
                            {{ result.object.category.name }}</a></span>
                        <span class="post-date"><a href="#">
                            <time class="entry-date" datetime="{{ result.object.created_time }}">
                                {{ result.object.created_time }}</time></a></span>
                        <span class="post-author"><a href="#">{{ result.object.author }}</a></span>
                        <span class="comments-link">
                        <a href="{{ result.object.get_absolute_url }}#comment-area">
                            {{ result.object.comment_set.count }} 评论</a></span>
                        <span class="views-count">
                            <a href="{{ result.object.get_absolute_url }}">{{ result.object.views }} 阅读</a>
                        </span>
                    </div>
                </header>
                <div class="entry-content clearfix">
                    <p>{% highlight result.object.excerpt with query %}...</p>
                    <div class="read-more cl-effect-14">
                        <a href="{{ result.object.get_absolute_url }}" class="more-link">继续阅读
                            <span class="meta-nav">→</span>
                        </a>
                    </div>
                </div>
            </article>
        {% empty %}
            <div class="no-post">
                <br>
                <h3 style="text-align: center;">没有搜索到关键词内容，试试换个姿势？</h3>
                <br><br>
                <img class="img-responsive"
                     src="http://ww1.sinaimg.cn/large/8512ee6bly1fqrcelxbs7g206t041atb.gif"
                     alt="快去再搜一遍" width="100%">
            </div>
        {% endfor %}
        {% if page.has_previous or page.has_next %}
            <div>
                {% if page.has_previous %}
                    <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">{% endif %}&laquo; Previous
                {% if page.has_previous %}</a>{% endif %}
                |
                {% if page.has_next %}<a href="?q={{ query }}&amp;page={{ page.next_page_number }}">{% endif %}Next
                &raquo;{% if page.has_next %}</a>{% endif %}
            </div>
        {% endif %}
    {% else %}
        请输入搜索关键词
    {% endif %}
{% endblock main %}