blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2018/4/19 15:46
# @File    : urls.py

from django.conf.urls import url
from blog.feeds import AllPostsRssFeed
from . import views

app_name = 'blog'
urlpatterns = [
    # django2.0后使用path，不过用1.0的项目比较多
    # path('post/<int:pk>/', views.detail, name='detail'),
    # as_view将类视图转换为函数
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9])/$', views.TagView.as_view(), name="tag"),
    url(r'^about/$', views.aboutpage, name='about'),
    url(r'collection/$', views.collection, name='collection'),
    # 简单搜索
    # url(r'^search/$', views.search, name="search"),
    # RSS订阅
    url(r'^all/rss/$', AllPostsRssFeed(), name="rss"),
]

comments/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2018/4/20 16:04
# @File    : urls.py

from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    # haystack全局搜索
    path('search/', include('haystack.urls')),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.urls import reverse
from django.utils.html import strip_tags
import markdown


# Create your models here.


# 用装饰器兼容py2
@python_2_unicode_compatible
class Category(models.Model):
    """
    模型必须继承models.Model类
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Tag(models.Model):
    """
    标签
    """
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Post(models.Model):
    """
    文章内容相关
    """
    title = models.CharField(max_length=70)
    # 正文内容使用textfield
    body = models.TextField()
    # 时间使用Datetimefield
    create_time = models.DateField()
    modified_time = models.DateField()
    # 开头摘要，可为空
    excerpt = models.CharField(max_length=200, blank=True)
    """
    分类标签相关
    """
    # 分类类型为主键,on_delete=models.CASCADE
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 一篇文章对应多个标签，一个标签也对应多个文章，当然也能为空
    tags = models.ManyToManyField(Tag, blank=True)
    """
    文章作者，django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程
    on_delete=models.CASCADE
    也应该是个主键，参数是由user那边的传过来的
    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    # 阅读量，应该是个自增量，默认0
    views = models.PositiveIntegerField(default=0)

    # 调用此方法实现自增，数据库更新此字段
    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    def __str__(self):
        return self.title

    # 重写get_absolute_url，需要reverse函数
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 自动保存摘要，重写个save
    def save(self, *args, **kwargs):
        # 如果内容摘要为空
        if not self.excerpt:
            # 设置一个md配置
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 将md内容转换为html
            # django下的工具类中的strip_tags方法可以去除html的标签，顺便只取前54个字符
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 处理完成后使用父类中的save进行真正保存
        super(Post, self).save(*args, **kwargs)

    # 内部类，定义默认排序方式
    class Meta:
        ordering = ['-create_time', 'title']

comments/models.py
from django.db import models
from django.utils.six import python_2_unicode_compatible

# Create your models here.


@python_2_unicode_compatible
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    create_time = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blog/views.py
# -*- coding:utf-8 -*-

import markdown
from markdown.extensions.toc import TocExtension
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404
from django.utils.text import slugify
from django.db.models import Q
from .models import Post, Category, Tag
from comments.forms import CommentForm

# # 主页
# def index(request):
#     # -为反向，不加是正向
#     post_list = Post.objects.all()
#     return render(request, 'blog/index.html', context={'post_list': post_list})


# # 详情
# def detail(request, pk):
#     post = get_object_or_404(Post, pk=pk)
#     # 简化操作，打开详情即为阅读一次，自增一
#     post.increase_views()
#     # 使用markdown模块，防止转义前台页面要加'|safe'
#     post.body = markdown.markdown(
#         post.body, extensions=[
#             'markdown.extensions.extra',
#             # 语法高亮
#             'markdown.extensions.codehilite',
#             # 自动生成目录
#             'markdown.extensions.toc',
#         ]
#     )
#
#     # 同时获取post下的评论
#     comment_list = post.comment_set.all()
#     # 初始化form
#     form = CommentForm()
#
#     context = {
#         "post": post,
#         "form": form,
#         "comment_list": comment_list
#     }
#     return render(request, 'blog/detail.html', context=context)


# # 归档
# def archives(request, year, month):
#     post_list = Post.objects.filter(
#         create_time__year=year,
#         create_time__month=month
#     ).order_by('create_time')
#     return render(request, 'blog/index.html', context={"post_list": post_list})


# # 分类
# def category(request, pk):
#     cate = get_object_or_404(Category, pk=pk)
#     post_list = Post.objects.filter(category=cate)
#     return render(request, 'blog/index.html', context={"post_list": post_list})

# 关于
def aboutpage(request):
    return render(request, 'blog/about.html')


# 收藏
def collection(request):
    return render(request, 'blog/collection.html')


"""

以.下.为.主.要.类.视.图

"""


class IndexView(ListView):
    """
    index通用类视图，继承ListView
    """
    # 指定model为Post
    model = Post
    # 指定渲染的模板
    template_name = "blog/index.html"
    # 指定传递的变量名
    context_object_name = "post_list"
    # 指定分页器单页最大数据
    # 等价于 Paginator(list, pages_num)
    # 前台：
    # paginator：Paginator的实例。
    # page_obj：当前请求页面分页对象。
    # is_paginated：是否已分页（当分页后页面超过两页时才算已分页）
    paginate_by = 10

    # 以下为复杂分页，也就是先将所需数据生成，然后传递到模板中
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # 因为继承的是ListView，已有分页相关的三个变量
        paginator = context.get("paginator")
        page = context.get("page_obj")
        is_paginated = context.get("is_paginated")
        # 调用自己的分页方法
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将分页后的字典保存回context中
        context.update(pagination_data)
        return context

    def pagination_data(self, paginator, page, is_paginated):
        # 没有分页，返回空字典
        if not is_paginated:
            return {}
        # 分页条以中央位置为基准，需要记录左边有几个页码， 右边有几个页码
        left =[]
        right =[]
        # 第一页后是否需要...
        left_has_more = False
        # 最后一页前是否需要...
        right_has_more = False
        # 是否需要显示第一页的页码，当前左侧已有就不用显示
        first = False
        # 是否显示最后一页的页码，当前右侧已有就不用显示
        last = False
        # 用户选择的页码
        page_number = page.number
        # 总页数
        total_pages = paginator.num_pages
        # 分页条的列表
        page_range = paginator.page_range
        if page_range == 1:
            # 右侧显示当前页码之后的n个页码
            right = page_range[page_number:page_number+2]
            # 如果右侧最后一个页码比总页码倒数第二个还要少，则添加进...
            if right[-1] < total_pages-1:
                right_has_more =True
            # 如果右侧最后一个页码比总数小，说明右侧不含最后一个页码，需要显示
            if right[-1] <total_pages:
                last = True
        elif page_number == total_pages:
            # 如果用户选的是最后一页，右边就不需要数据，左边需要显示当前页码后连续n+1个页码
            left = page_range[(page_number-3) if (page_number-3) > 0 else 0: page_number-1]
            # 如果left的第一个页码比n还大，则需要显示...
            if left[0] > 2:
                left_has_more = True
            # 如果left的第一个页码比1大，则left不包含第一页页码，需要显示
            if left[0] > 1:
                first =True
        else:
            # 用户随便点了一页
            left = page_range[(page_number-3) if (page_number-3) > 0 else 0: page_number-1]
            right = page_range[page_number:page_number+2]
            # 最后一页之前的...
            if right[-1] < total_pages-1:
                right_has_more = True
            # 是否显示最后的页码
            if right[-1] < total_pages:
                last = True
            # 第一页之后的...
            if left[0] > 2:
                left_has_more = True
            # 是否显示第一页页码
            if left[0] > 1:
                first = True

        # 返回的结果
        data = {
            "left": left,
            "right": right,
            "left_has_more": left_has_more,
            "right_has_more": right_has_more,
            "first": first,
            "last": last
        }
        return data


class CategoryView(IndexView):
    """
    category分类视图继承自index类视图
    """
    # 重写queryset方法，改变数据获取方式
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get("pk"))
        # 再执行父类的filter方法
        # return super(CategoryView, self).get_queryset().filter(category=cate)
        # 同等
        return Post.objects.filter(category=cate)


class ArchivesView(IndexView):
    """
    archives归档视图继承自index类视图
    """
    def get_queryset(self):
        year = self.kwargs.get("year")
        month = self.kwargs.get("month")
        return super(ArchivesView, self).get_queryset().filter(
            create_time__year=year,
            create_time__month=month
        )


class PostDetailView(DetailView):
    """
    单条详情数据需要继承自DetailView类
    """
    model = Post
    template_name = "blog/detail.html"
    context_object_name = "post"

    def get(self, request, *args, **kwargs):
        """
        重写get方法
        最后返回个HttpResponse
        当get被调用后才会有self.object，即为单条post
        """
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        # 阅读量+1
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        """
        重写get_object，需要对模板内容进行渲染
        :param queryset:
        :return:
        """
        post = super(PostDetailView, self).get_object(queryset=None)
        # 使用markdown模块，防止转义前台页面要加'|safe'
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            # 语法高亮
            'markdown.extensions.codehilite',
            # 自动生成目录锚点
            # 'markdown.extensions.toc',
            # 自定义锚点实例化，slugify方法处理中文
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        """
        重写get_context_data，不仅将post内容传到模板，还需要把form的实例传到前台
        :param kwargs:
        :return:
        """
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm
        comment_list = self.object.comment_set.all()
        context.update({
            "form": form,
            "comment_list": comment_list
        })
        return context


class TagView(IndexView):
    """
    标签视图类
    """
    def get_queryset(self):
        """
        重写get_queryset
        :return:
        """
        tag = get_object_or_404(Tag, pk=self.kwargs.get("pk"))
        return super(TagView, self).get_queryset().filter(tags=tag)


# 简单搜索方法
def search(request):
    """
    Q对象
    :param request:
    :return:
    """
    q = request.GET.get("q")
    error_msg = ""
    if not q:
        error_msg = "请输入关键词"
        return render(request, "blog/index.html", {"error_msg": error_msg})
    # __icontains包含，Q对象包装复杂查询，比如或'|'
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, "blog/index.html", {
        "error_msg": error_msg,
        "post_list": post_list
    })

templates/blog/about.html
{% extends 'base.html' %}

{% block main %}
    <h1 class="page-title">About Me</h1>
	    <article class="post">
            <div class="entry-content clearfix">
                <figure class="img-responsive-center">
                    <img class="img-responsive"
                         src="http://ww1.sinaimg.cn/large/8512ee6bly1fqrce4us6hj20i20bot97.jpg"
                         alt="海豹仔">
                </figure>
				<p>
                    &nbsp;&nbsp;&nbsp;&nbsp;竖琴海豹（学名：Pagophilus groenlandicus）体长1.7米，体重130千克。面部宽阔，两眼靠近，强壮而呈黑色的爪子，银白色而光滑的皮毛。明显的黑色条带在背部形成许多鞍纹，大体呈竖琴图案。
<br>
&nbsp;&nbsp;&nbsp;&nbsp;竖琴海豹是一种相当耐寒的海洋哺乳动物。主要分布于亚特兰大以北到北冰洋间的极地地区。生活于极地的开阔海洋和海岸线边缘地带。以鳕鱼、香鱼和鲱鱼等为食。通常以集群的形式沿着冰带的边缘大规模迁移。
<br>
&nbsp;&nbsp;&nbsp;&nbsp;由于其皮毛和海豹油的价值而长期处于被捕猎状态。从1987年开始，加拿大《海洋哺乳动物条例》禁止捕猎竖琴海豹幼崽（白毛海豹），捕猎的海豹必须是能自我生存和能独立生活的海豹（通常年龄在25天以上）。
                </p>
				<div class="height-40px"></div>
                <h2 class="title text-center">Social</h2>
                <ul class="social">
                    <li class="twitter">
                        <a href="https://twitter.com/QuantaZero">
                            <span class="ion-social-twitter"></span>
                        </a>
                    </li>
                    <li class="twitter">
                        <a href="https://t.me/tenshin">
                            <span class="ion-paper-airplane"></span>
                        </a>
                    </li>
                </ul>
            </div>
        </article>
{% endblock main %}

templates/blog/collection.html
{% extends 'base.html' %}
{% block main %}
    <h1 class="page-title">网站收集</h1>
    <p>
        诶，我还没想好搞什么
    </p>
{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}
        {% block main %}
                <article class="post post-{{ post.pk }}">
                    <header class="entry-header">
                        <h1 class="entry-title">{{ post.title }}</h1>
                        <div class="entry-meta">
                            <span class="post-category"><a href="javascript:void(0);">{{ post.category.name }}</a></span>
                            <span class="post-date">
                                <a href="javascript:void(0);">
                                    <time class="entry-date" datetime="{{ post.create_time }}">
                                        {{ post.create_time }}
                                    </time>
                                </a>
                            </span>
                            <span class="post-author"><a href="javascript:void(0);">{{ post.author }}</a></span>
                            <span class="comments-link"><a href="javascript:void(0);">{{ post.comment_set.count }} 评论</a></span>
                            <span class="views-count"><a href="javascript:void(0);">{{ post.views }} 阅读</a></span>
                        </div>
                        <hr>
                        <div class="widget-tag-cloud">
                            <ul>
                                相关标签：
                                {% for tag in post.tags.all %}
                                    <li>
                                        <a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </header>
                    <br>
                    <div class="entry-content clearfix">
                        {{ post.body|safe }}
                    </div>
                </article>


                <section class="comment-area" id="comment-area">
                    <hr><hr>
                    <div class="comment-list-panel">
                        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
                        <ul class="comment-list list-unstyled">
                            {% for comment in comment_list %}
                            <li class="comment-item">
                                <span class="nickname">{{ comment.name }}</span>
                                <time class="submit-date" datetime="{{ comment.create_time }}">
                                    {{ comment.create_time }}
                                </time>
                                <div class="text">{{ comment.text }}</div>
                            </li>
                            {% empty %}
                                暂无评论，就等你了  (´・ω・｀)
                            {% endfor %}
                        </ul>
                    </div>
                    <hr>
                    <h3>发表评论</h3>
                    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-4">
                                <label for="id_name">名字：</label>
                                {{ form.name }}
                                {{ form.name.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_email">邮箱：</label>
                                {{ form.email }}
                                {{ form.email.errors }}
                            </div>
                            <div class="col-md-4">
                                <label for="id_url">网址：</label>
                                {{ form.url }}
                                {{ form.url.errors }}
                            </div>
                            <div class="col-md-12">
                                <label for="id_comment">评论：</label>
                                {{ form.text }}
                                {{ form.text.errors }}
                                <button type="submit" class="comment-btn">发表</button>
                            </div>
                        </div>    <!-- row -->
                    </form>
                </section>
                {% endblock main %}



            {% block toc %}
                <div class="widget widget-content">
                    <h3 class="widget-title">文章目录</h3>
                    {{ post.toc|safe }}
                    <hr>
                </div>
            {% endblock toc %}

templates/blog/full-width.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body>
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="collection.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<article class="post post-1">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-2">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-3">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>

						<article class="post post-4">
							<header class="entry-header">
								<h1 class="entry-title">
									<a href="detail.html">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>
								</h1>
								<div class="entry-meta">
									<span class="post-category"><a href="#" rel="category tag">Web Design</a></span>
			
									<span class="post-date"><a href="#"><time class="entry-date" datetime="2012-11-09T23:15:57+00:00">February 2, 2013</time></a></span>
			
									<span class="post-author"><a href="#">Albert Einstein</a></span>
			
									<span class="comments-link"><a href="#">4 Comments</a></span>
								</div>
							</header>
							<div class="entry-content clearfix">
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="read-more cl-effect-14">
									<a href="#" class="more-link">Continue reading <span class="meta-nav">→</span></a>
								</div>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="collection.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>

	</body>
</html>

templates/blog/index.html
{% extends 'base.html' %}

            {% block main %}
                {% if error_msg %}
                    <p>{{ error_msg }}</p>
                {% endif %}

                {% for post in post_list %}
                    <article class="post post-{{ post.pk }}">
                        <header class="entry-header">
                            <h1 class="entry-title">
                                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                            </h1>
                            <div class="entry-meta">
                                <span class="post-category"><a href="javascript:void(0);">{{ post.category.name }}</a></span>
                                <span class="post-date">
                                    <a href="javascript:void(0);">
                                        <time class="entry-date" datetime="{{ post.create_time }}">
                                            {{ post.create_time }}
                                        </time>
                                    </a>
                                </span>
                                <span class="post-author"><a href="javascript:void(0);">{{ post.author }}</a></span>
                                <span class="comments-link"><a href="javascript:void(0);">{{ post.comment_set.count }} 评论</a></span>
                                <span class="views-count"><a href="javascript:void(0);">{{ post.views }} 阅读</a></span>
                            </div>
                        </header>
                        <div class="entry-content clearfix">
                            <p>{{ post.excerpt }}...</p>
                            <div class="read-more cl-effect-14">
                                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                            </div>
                        </div>
                    </article>
                {% empty %}
                    <div class="no-post">暂时还没有发布的文章！</div>
                {% endfor %}


{#                {% if is_paginated %}#}
{#                <div class="pagination-simple">#}
{#                    {% if page_obj.has_previous %}#}
{#                    <a href="?page={{ page_obj.previous_page_number }}">上一页</a>#}
{#                    {% endif %}#}
{#                    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>#}
{#                    {% if page_obj.has_next %}#}
{#                    <a href="?page={{ page_obj.next_page_number }}">下一页</a>#}
{#                    {% endif %}#}
{#                </div>#}
{#                {% endif %}#}


                {% if is_paginated %}
                <div class="pagination">
                    {% if first %}
                        <a href="?page=1">1</a>
                    {% endif %}
                    {% if left %}
                        {% if left_has_more %}
                            <span>...</span>
                        {% endif %}
                        {% for i in left %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                    {% endif %}
                    <a class="current-page" href="?page={{ page_obj.number }}" >{{ page_obj.number }}</a>
                    {% if right %}
                        {% for i in right %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endfor %}
                        {% if right_has_more %}
                            <span>...</span>
                        {% endif %}
                    {% endif %}
                    {% if last %}
                        <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                </div>
                {% endif %}

            {% endblock main %}