blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2018/4/19 15:46
# @File    : urls.py

from django.conf.urls import url
from blog.feeds import AllPostsRssFeed
from . import views

app_name = 'blog'
urlpatterns = [
    # django2.0后使用path，不过用1.0的项目比较多
    # path('post/<int:pk>/', views.detail, name='detail'),
    # as_view将类视图转换为函数
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9])/$', views.TagView.as_view(), name="tag"),
    url(r'^about/$', views.aboutpage, name='about'),
    url(r'collection/$', views.collection, name='collection'),
    # 简单搜索
    # url(r'^search/$', views.search, name="search"),
    # RSS订阅
    url(r'^all/rss/$', AllPostsRssFeed(), name="rss"),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
    # haystack全局搜索
    path('search/', include('haystack.urls')),
]

templates/base.html
{% load static from staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>IDOLA</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- ico -->
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" />

    <!-- css -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
{#    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">#}
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- 语法高亮 -->
    <link rel="stylesheet" href="{% static 'css/highlights/github.css' %}">
    <!-- 简单样式设置 -->
    <link rel="stylesheet" href="{% static 'css/simple_style.css' %}">

    <!-- js -->
{#    <script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
{#    <script src="{% static 'js/bootstrap.min.js' %}"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/pace.min.js' %}"></script>
    <script src="{% static 'js/modernizr.custom.js' %}"></script>


</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>IDOLA</b>&nbsp;&amp;&nbsp;TRUTH</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'blog:collection' %}" data-hover="收藏">收藏</a></li>
                            <li class="cl-effect-11">
                                <a href="http://www.theuselessweb.com/" target="_blank" data-hover="摸鱼">摸鱼</a>
                            </li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="javascript:void(0);" title="点击开始搜索">
                        <span id="search-icon" class="ion-ios-search-strong"></span>
                    </a>
                    <div id="search-form" class="search-form" >
{#                        <form role="search" method="get" id="searchform" action="{% url 'blog:search' %}">#}
                        <form role="search" method="get" id="searchform" action="{% url 'haystack_search' %}">
                            <input type="search" name="q" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>


<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>
{#            <main class="col-md-12">#}
{#                {% block about %}#}
{#                {% endblock about %}#}
{#            </main>#}
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_posts as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                        </li>
                        {% empty %}
                            暂无文章 ( ^ω^ )
                        {% endfor %}
                    </ul>
                </div>
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">
                                {{ date.year }} 年 {{ date.month }} 月
                            </a>
                        </li>
                        {% empty %}
                            暂无归档  (´・ω・｀)
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">
                                {{ category.name }}
                                <span class="post-count">({{ category.num_posts }})</span>
                            </a>
                        </li>
                        {% empty %}
                            暂无分类  (´・ω・｀)
                        {% endfor %}
                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签</h3>
                    {% get_tags as tag_list %}
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                        </li>
                        {% empty %}
                            暂无标签  (´・ω・｀)
                        {% endfor %}
                    </ul>
                </div>
                <div class="rss">
                    <a href="{% url 'blog:rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">
                    &copy 2017
                </p>
                <p style="text-align:center;display:none;">

                    你发现了个彩蛋，哦不是，彩苹果

                         -/+:.          arks@AIS
                        :++++.          OS: 64bit Mac OS X 10.13.4 17E199
                       /+++/.           Kernel: x86_64 Darwin 17.5.0
               .:-::- .+/:-``.::-       Uptime: 1h 1m
            .:/++++++/::::/++++++/:`    Packages: 55
          .:///////////////////////:`   Shell: zsh 5.5.1
          ////////////////////////`     Resolution: 2880x1800
         -+++++++++++++++++++++++`      DE: Aqua
         /++++++++++++++++++++++/       WM: Quartz Compositor
         /sssssssssssssssssssssss.      WM Theme: Blue
         :ssssssssssssssssssssssss-     CPU: Intel Core i7-7820HQ @ 2.90GHz
          osssssssssssssssssssssssso/`  GPU: Intel HD Graphics 630 / Radeon Pro 560
          `syyyyyyyyyyyyyyyyyyyyyyyy+`  RAM: 10058MiB / 16384MiB
           `ossssssssssssssssssssss/
             :ooooooooooooooooooo+.
              `:+oo+/:-..-:/+o+/-


                </p>
                <p style="text-align:center;display:none;">
                    页面模板来源：
                        采集自 http://www.cssmoban.com/ 模板之家
                        由 http://zmrenwu.com/ 追梦人物的博客 修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'blog:index' %}">首页</a></li>
            <li><a href="{% url 'blog:about' %}">关于</a></li>
            <li><a href="{% url 'blog:collection' %}">收藏</a></li>
            <li><a href="http://www.theuselessweb.com/" target="_blank" >摸鱼</a></li>
        </ul>
    </nav>
</div>

<!-- 一部分点击操作 -->
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>